name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.400

      - name: Setup dotnet tools
        run: dotnet tool restore

      - name: Install dependencies
        run: dotnet restore

      - name: Check formatting
        run: dotnet fantomas . -r --check

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test
